ci:
  autofix_commit_msg: "ci(pre-commit): auto fix code"
  autofix_prs: true
  autoupdate_commit_msg: "ci(pre-commit): update pre-commit dependencies"
  autoupdate_schedule: weekly
  skip: [fmt, cargo-check, clippy]
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-vcs-permalinks
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent=2]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
